// lib/data/dsa_data.dart

final Map<String, List<String>> dsaSections = {
  "Arrays & Lists": [
    "Two Sum",
    "Best Time to Buy and Sell Stock",
    "Contains Duplicate",
    "Move Zeroes",
    "Remove Duplicates from Sorted Array",
    "3Sum",
    "Merge Intervals",
    "Product of Array Except Self",
    "Trapping Rain Water",
    "Median of Two Sorted Arrays",
  ],
  "Strings": [
    "Valid Anagram",
    "Reverse String",
    "Valid Palindrome",
    "Longest Common Prefix",
    "Implement strStr()",
    "Longest Substring Without Repeating",
    "Group Anagrams",
    "String Compression",
    "Minimum Window Substring",
    "Regular Expression Matching",
  ],
  "HashMap / HashSet": [
    "Two Sum (Map)",
    "Happy Number",
    "Isomorphic Strings",
    "Word Pattern",
    "Contains Duplicate II",
    "Subarray Sum Equals K",
    "Top K Frequent Elements",
    "Group Anagrams",
    "LRU Cache",
    "Minimum Window Subsequence",
  ],
  "Stacks & Queues": [
    "Valid Parentheses",
    "Min Stack",
    "Implement Queue using Stacks",
    "Implement Stack using Queues",
    "Next Greater Element I",
    "Daily Temperatures",
    "Decode String",
    "Simplify Path",
    "Basic Calculator II",
    "Largest Rectangle in Histogram",
  ],
  "Trees & Recursion": [
    "Maximum Depth of Binary Tree",
    "Same Tree",
    "Symmetric Tree",
    "Invert Binary Tree",
    "Path Sum",
    "Binary Tree Level Order Traversal",
    "Lowest Common Ancestor of BST",
    "Construct Binary Tree from Preorder/Inorder",
    "Serialize & Deserialize Binary Tree",
    "Binary Tree Maximum Path Sum",
  ],
  "Linked Lists": [
    "Reverse Linked List",
    "Merge Two Sorted Lists",
    "Linked List Cycle",
    "Remove Nth Node from End",
    "Palindrome Linked List",
    "Add Two Numbers",
    "Odd Even Linked List",
    "Rotate List",
    "Merge k Sorted Lists",
    "Reverse Nodes in k-Group",
  ],
  "Searching & Sorting": [
    "Binary Search",
    "Search Insert Position",
    "First Bad Version",
    "Squares of a Sorted Array",
    "Merge Sorted Array",
    "Search in Rotated Sorted Array",
    "Kth Largest Element in Array",
    "Sort Colors",
    "Find Median from Data Stream",
    "Sliding Window Maximum",
  ],
  "Dynamic Programming": [
    "Climbing Stairs",
    "House Robber",
    "Maximum Subarray",
    "Min Cost Climbing Stairs",
    "Fibonacci Number",
    "Coin Change",
    "Longest Increasing Subsequence",
    "Partition Equal Subset Sum",
    "Word Break II",
    "Edit Distance",
  ],
  "Graphs": [
    "Find the Town Judge",
    "Flood Fill",
    "Number of Islands",
    "Max Area of Island",
    "Valid Path",
    "Course Schedule",
    "Clone Graph",
    "Rotting Oranges",
    "Word Ladder",
    "Alien Dictionary",
  ],
  "Real-World Logic": [
    "Valid Sudoku",
    "Majority Element",
    "Intersection of Two Arrays",
    "Single Number",
    "Missing Number",
    "Task Scheduler",
    "Meeting Rooms II",
    "Insert Interval",
    "N-Queens",
    "Merge k Sorted Lists",
  ],
};
